#!/usr/bin/env python3
"""
dev-assistant — implementation planning chatbot for any project.
Reads config.json (generated by connect.ps1 / connect.sh).

Run:   python server.py
Open:  http://localhost:<port from config>
"""

import json, os, subprocess, sys, tempfile, threading, time
from http.server import BaseHTTPRequestHandler, HTTPServer
try:
    from watchdog.observers import Observer
    from watchdog.events import FileSystemEventHandler
except ImportError:
    Observer = None

HERE = os.path.dirname(os.path.abspath(__file__))
CONFIG_PATH = os.path.join(os.getcwd(), "dev-assistant.json")
if not os.path.exists(CONFIG_PATH):
    CONFIG_PATH = os.path.join(HERE, "config.json")

# ── Load config ───────────────────────────────────────────────────────────────
def load_config() -> dict:
    if not os.path.exists(CONFIG_PATH):
        print(f"\n  ERROR: Configuration not found!")
        print(f"  We looked for: {os.path.join(os.getcwd(), 'dev-assistant.json')}")
        print(f"  Make sure you run `npx dev-assistant serve` from the root of your project.")
        sys.exit(1)
    with open(CONFIG_PATH, encoding="utf-8") as f:
        return json.load(f)

cfg  = load_config()
PORT = cfg.get("port", 8765)
GRAPH = cfg["graphPath"]
ROOT  = cfg["projectRoot"]

PROJECT_CONTEXT = f"""
PROJECT: {cfg.get("projectName", "Unknown")}

TECH STACK:
{cfg.get("techStack", "")}

BACKEND PATTERN:
{cfg.get("backendPattern", "")}

FRONTEND PATTERN:
{cfg.get("frontendPattern", "")}

API ROUTE PATTERN:
{cfg.get("apiPattern", "/api/v1/<resource>")}

ARCHITECTURE RULES (never violate):
{chr(10).join(f"- {r}" for r in cfg.get("architectureRules", []))}

MANDATORY ENGINEERING RULES:
- NEVER_BREAK_EXISTING_FUNCTIONALITY: Every code change must preserve existing working behavior, preserve API contracts, and pass graphify regression checks.
- ALWAYS_VERIFY_LATEST_CONTEXT: Query the latest graphify graph and inspect dependent modules before modifying files.
- SENIOR_ENGINEER_SURGICAL_EDITS: Make minimal surgical edits, maximize reuse, and avoid unnecessary refactoring.

GOLDEN MODULE (simple CRUD reference):
{cfg.get("goldenModuleSimple", "not configured")}

GOLDEN MODULE (wizard / complex form reference):
{cfg.get("goldenModuleWizard", "not configured")}

EXISTING FEATURES (do not re-implement these):
{", ".join(cfg.get("existingFeatures", []))}
""".strip()

# ── Intent detection ──────────────────────────────────────────────────────────
ORIENT_KEYWORDS = [
    "what is this project", "what does this project do", "what does this app do",
    "give me an overview", "project overview", "high level overview",
    "architecture overview", "how is this organized", "how is the codebase organized",
    "where do i start", "where should i start", "new here", "new to this project",
    "new to this codebase", "onboarding", "getting started", "get started",
    "tell me about this project", "walk me through this", "introduce me to this project",
    "i'm new", "im new", "just joined",
]
PLAN_KEYWORDS = [
    "add", "create", "build", "implement", "develop", "make",
    "new feature", "new module", "new page",
    "want to", "need to", "i want", "i need",
    "how to add", "how do i add", "how can i add",
]
IMPACT_KEYWORDS = [
    "change", "modify", "update", "edit", "refactor", "rename",
    "what happens", "what will break", "impact", "affect", "break",
    "safe to change", "side effect",
]

def detect_intent(q: str) -> str:
    ql = q.lower()
    if any(k in ql for k in ORIENT_KEYWORDS):
        return "orient"
    if any(k in ql for k in PLAN_KEYWORDS):
        return "plan"
    if any(k in ql for k in IMPACT_KEYWORDS):
        return "impact"
    return "explain"


# ── Subprocess helpers ────────────────────────────────────────────────────────
def _run(cmd: list, stdin_text: str = None, timeout: int = 60) -> str:
    """Run a command, optionally with stdin. Returns stdout+stderr as string."""
    try:
        kwargs = dict(capture_output=True, text=True, encoding="utf-8",
                      errors="replace", cwd=ROOT, timeout=timeout)
        if stdin_text is not None:
            kwargs["input"] = stdin_text
        r = subprocess.run(cmd, **kwargs)
        return ((r.stdout or "") + (r.stderr or "")).strip()
    except Exception as e:
        return f"[error: {e}]"


def gq(query: str, limit: int = 2000) -> str:
    """Query the graphify knowledge graph."""
    out = _run(["graphify", "query", query, "--graph", GRAPH], timeout=60)
    return out[:limit] if len(out) > limit else out


def _run_claude(prompt: str, timeout: int = 120) -> str:
    """Send a prompt to Claude via temp-file stdin (avoids Windows CLI length limit)."""
    tmp = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".txt", delete=False, encoding="utf-8"
        ) as f:
            f.write(prompt)
            tmp = f.name
        with open(tmp, "r", encoding="utf-8") as stdin_f:
            r = subprocess.run(
                ["claude", "--print"],
                stdin=stdin_f,
                capture_output=True, text=True, encoding="utf-8", errors="replace",
                cwd=ROOT, timeout=timeout,
            )
        return (r.stdout or "").strip()
    except Exception as e:
        return f"[claude error: {e}]"
    finally:
        if tmp:
            try:
                os.unlink(tmp)
            except Exception:
                pass


# ── Entity name extraction (plan mode) ───────────────────────────────────────
def extract_entity_name(question: str) -> tuple:
    mini = (
        f'From this requirement: "{question[:400]}"\n'
        "Reply with exactly 3 lines (no explanation):\n"
        "Line 1: PascalCase entity name (e.g. Patient)\n"
        "Line 2: kebab-case plural route (e.g. patients)\n"
        "Line 3: simple or wizard"
    )
    try:
        raw = _run_claude(mini, timeout=30)
        lines = [l.strip() for l in raw.splitlines()
                 if l.strip() and not l.startswith("[")]
        if len(lines) >= 3:
            return lines[0], lines[1], lines[2]
        if len(lines) >= 2:
            return lines[0], lines[1], "simple"
        if lines:
            name = lines[0]
            return name, name.lower() + "s", "simple"
    except Exception:
        pass
    return "Entity", "entities", "simple"


# ── Curated onboarding context (for "orient") ────────────────────────────────
def _read_file_safe(path: str, limit: int = 2500) -> str:
    try:
        with open(path, encoding="utf-8") as f:
            text = f.read()
        return text[:limit]
    except Exception:
        return ""


def gather_orient_context(question: str = "") -> str:
    """Prefer curated, human-written project docs over raw graph queries —
    they're what a newcomer should read first, not a noisy graph dump."""
    parts = []

    mem_dir = cfg.get("memoryDir", "")
    if mem_dir:
        snap = _read_file_safe(os.path.join(mem_dir, "project-context-snapshot.md"), 3000)
        if snap:
            parts.append(f"=== PROJECT MEMORY SNAPSHOT (dev-assistant) ===\n{snap}")

    doc_candidates = [
        os.path.join(ROOT, "docs", "ai-context", "FEATURE_INVENTORY.md"),
        os.path.join(ROOT, "docs", "ai-context", "INDEX.md"),
        os.path.join(ROOT, "PROJECT_MEMORY.md"),
        os.path.join(ROOT, "CLAUDE.md"),
        os.path.join(ROOT, "README.md"),
    ]
    for path in doc_candidates:
        text = _read_file_safe(path, 2000)
        if text:
            parts.append(f"=== {os.path.basename(path)} ===\n{text}")

    if not parts:
        parts.append(f"=== KNOWLEDGE GRAPH (fallback — no curated docs found) ===\n"
                      f"{gq('project overview architecture main modules', 2500)}")

    if question:
        parts.append(f"=== RELEVANT CODE CONTEXT FOR THIS QUESTION ===\n{gq(question, 1200)}")

    return "\n\n".join(parts)


def is_context_thin(graph_data: str) -> bool:
    """Heuristic: strip section headers and see how much real signal is left."""
    signal = re_sub_headers(graph_data)
    return len(signal.strip()) < 300


def re_sub_headers(text: str) -> str:
    return "\n".join(line for line in text.splitlines() if not line.startswith("==="))


# ── Graph context gathering ───────────────────────────────────────────────────
def gather_context(question: str, intent: str) -> str:
    parts = []
    if intent == "orient":
        parts.append(gather_orient_context(question))
    elif intent == "plan":
        parts.append(f"=== SIMILAR EXISTING PATTERNS ===\n{gq(question, 1500)}")
        parts.append(f"=== BACKEND SERVICE PATTERN ===\n{gq('backend service controller interface pattern', 1000)}")
        parts.append(f"=== FRONTEND COMPONENT PATTERN ===\n{gq('frontend page component service standalone', 1000)}")
    elif intent == "impact":
        parts.append(f"=== CURRENT STATE ===\n{gq(question, 1500)}")
        parts.append(f"=== CALLERS & DEPENDENCIES ===\n{gq(f'{question} callers imports depends', 1500)}")
    else:
        parts.append(f"=== KNOWLEDGE GRAPH ===\n{gq(question, 2500)}")
    return "\n\n".join(parts)


# ── Audience + honesty + conversation-history helpers ────────────────────────
AUDIENCE_GUIDANCE = {
    "candidate": (
        "Audience: a job candidate interviewing for a role on this project, evaluating "
        "whether they understand and can talk about it. Use plain English, no internal "
        "jargon, no file paths or class names — focus on what the product does, who uses "
        "it, and why it's built the way it is. Keep it welcoming and concise."
    ),
    "new_hire": (
        "Audience: a new employee in their first week on this project. Be concrete — name "
        "real features and modules and roughly where they live — but still explain any "
        "acronym or internal term the first time you use it."
    ),
    "engineer": (
        "Audience: an experienced engineer ramping up on this codebase. Be technical and "
        "specific — exact file paths, class/service names, and architecture details are "
        "expected and welcome."
    ),
}

def audience_line(audience: str) -> str:
    return AUDIENCE_GUIDANCE.get(audience, AUDIENCE_GUIDANCE["new_hire"])


HONESTY_RULE = (
    "HONESTY RULE: If the codebase context below is thin, empty, or doesn't clearly relate "
    "to the question, say so explicitly at the start of your answer and give your best "
    "high-level answer based on the architecture rules/tech stack instead of inventing "
    "specific file names, class names, or claims the context doesn't support."
)


def build_history_text(history: list) -> str:
    if not history:
        return ""
    lines = ["=== CONVERSATION SO FAR (most recent last, use for follow-up context) ==="]
    for turn in history[-6:]:
        role = "User" if turn.get("role") == "user" else "Assistant"
        content = (turn.get("content") or "").strip()[:500]
        if content:
            lines.append(f"{role}: {content}")
    return "\n".join(lines) if len(lines) > 1 else ""


# ── Prompt builders ───────────────────────────────────────────────────────────
def build_orient_prompt(question: str, graph_data: str, audience: str, history_text: str) -> str:
    return f"""You are helping someone get oriented on the {cfg.get("projectName","project")} project.

{PROJECT_CONTEXT}

{audience_line(audience)}

{HONESTY_RULE}

PROJECT CONTEXT (curated docs + relevant code):
{graph_data[:3500]}

{history_text}

QUESTION: "{question}"

Answer in plain English, in short paragraphs or a short bulleted list — this is someone's
first real look at the project, not a technical deep-dive. If this is a broad "what is this
project" style question, cover: what the product does, who uses it, the tech stack, and
2-3 good follow-up questions they could ask next. If it's a follow-up drilling into a
specific feature or module, focus tightly on that instead of repeating the overview.
"""


def build_plan_prompt(question: str, entity: str, kebab: str,
                      page_type: str, graph_data: str, audience: str, history_text: str) -> str:
    e, k = entity, kebab
    el = e.lower()
    wizard_extra = ""
    if page_type == "wizard":
        wizard_extra = (
            f"\n- `[frontend path]/{k}-wizard-page.component.ts` — multi-step wizard"
            f"\n- `[frontend path]/{k}-wizard-page.component.html`"
        )

    return f"""You are a senior developer on the {cfg.get("projectName","project")} project.

{PROJECT_CONTEXT}

{audience_line(audience)}

{HONESTY_RULE}

CODEBASE GRAPH (similar patterns found):
{graph_data[:2500]}

{history_text}

USER REQUIREMENT: "{question}"
ENTITY: {e} | ROUTE: {cfg.get("apiPattern","").replace("<resource>", k)} | TYPE: {page_type}

Start your response with ## immediately. No intro. Fill in real paths based on the project's actual directory layout visible in the graph data.

## Files to Create
### Backend
- Entity class for {e} — no ORM attributes, plain properties
- Contracts file — request/response records
- Service interface — CRUD + status + delete
- Service implementation — uses the project DB context
- Controller — REST endpoints at {cfg.get("apiPattern","").replace("<resource>", k)}

### Frontend
- Model file — TypeScript interfaces
- Service file — HTTP calls wrapping the API
- List page component — uses existing shared table/dialog wrappers
- List page template{wizard_extra}

## Files to Modify
List each existing file with ONE specific line describing what changes.

## Impact & Risk
2-4 sentences: migration risks, FK risks, permission seeding, anything that could break existing code.

## Implementation Order
Numbered steps in the safe order to implement this from scratch.

## Key Files to Study First
2-4 existing files to clone/read before starting (use the graph data to find the best references).
"""


def build_impact_prompt(question: str, graph_data: str, audience: str, history_text: str) -> str:
    return f"""You are a senior developer on the {cfg.get("projectName","project")} project.

{PROJECT_CONTEXT}

{audience_line(audience)}

{HONESTY_RULE}

CODEBASE GRAPH:
{graph_data[:2500]}

{history_text}

CHANGE REQUEST: "{question}"

Start immediately with ##. No intro text.

## What Changes
Exactly what needs to change in the target file/class.

## Impact Map
One line per affected file:
- `path/to/file` — how affected — High / Medium / Low risk

## Breaking Risk
Numbered list, most risky first.

## Safe Implementation Steps
Numbered steps to make this change without breaking existing functionality.

## Test Checklist
- [ ] specific things to verify after the change
"""


def build_explain_prompt(question: str, graph_data: str, audience: str, history_text: str) -> str:
    return f"""You are a helpful developer explaining the {cfg.get("projectName","project")} codebase.

{PROJECT_CONTEXT}

{audience_line(audience)}

{HONESTY_RULE}

CODEBASE GRAPH:
{graph_data}

{history_text}

QUESTION: "{question}"

Answer in plain English. Reference specific file names and class names from the graph.
3-6 sentences. If the graph data was not relevant, explain from the architecture rules above.
"""


# ── Main ask handler ──────────────────────────────────────────────────────────
def handle_question(question: str, history: list = None, audience: str = "new_hire") -> dict:
    intent = detect_intent(question)
    graph_data = gather_context(question, intent)
    history_text = build_history_text(history or [])

    if is_context_thin(graph_data):
        graph_data = ("[NOTE: little grounded context was found for this question — "
                       "be upfront about that rather than guessing specifics.]\n\n") + graph_data

    if intent == "plan":
        entity, kebab, page_type = extract_entity_name(question)
        prompt = build_plan_prompt(question, entity, kebab, page_type, graph_data, audience, history_text)
    elif intent == "impact":
        prompt = build_impact_prompt(question, graph_data, audience, history_text)
    elif intent == "orient":
        prompt = build_orient_prompt(question, graph_data, audience, history_text)
    else:
        prompt = build_explain_prompt(question, graph_data, audience, history_text)

    answer = _run_claude(prompt, timeout=120)
    if not answer or answer.startswith("[claude error:"):
        answer = "No response from Claude. Check that `claude` is in your PATH."

    return {"answer": answer, "intent": intent}


# ── Getting Started (cached onboarding overview + suggestions) ──────────────
_getting_started_cache = None

def build_getting_started() -> dict:
    global _getting_started_cache
    if _getting_started_cache is not None:
        return _getting_started_cache

    graph_data = gather_orient_context()
    prompt = f"""You are writing a short welcome overview of the {cfg.get("projectName","project")} project
for someone who just opened this chatbot for the very first time — could be a job candidate
or a brand-new employee.

{PROJECT_CONTEXT}

PROJECT CONTEXT:
{graph_data[:3000]}

Write 4-6 plain-English sentences covering: what the product does, who uses it, and the
tech stack. No headers, no markdown, no file paths — just warm, clear prose. Return ONLY
the overview text, nothing else."""

    overview = _run_claude(prompt, timeout=60)
    if not overview or overview.startswith("[claude error:"):
        overview = (
            f"Hi! I'm connected to the {cfg.get('projectName', 'this')} codebase "
            f"({cfg.get('techStack', 'stack not configured')}). Ask me anything to get started."
        )

    features = cfg.get("existingFeatures", [])[:3]
    suggestions = [f"How does {f} work?" for f in features]
    suggestions += [
        "What's the tech stack and why was it chosen?",
        "How is the codebase organized?",
        "Where should I start reading the code?",
    ]

    _getting_started_cache = {"overview": overview.strip(), "suggestions": suggestions[:6]}
    return _getting_started_cache


# ── Graph info ────────────────────────────────────────────────────────────────
def graph_node_count() -> int:
    try:
        with open(GRAPH, encoding="utf-8") as f:
            return len(json.load(f).get("nodes", []))
    except Exception:
        return 0


# ── Embedded HTML ─────────────────────────────────────────────────────────────
HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>dev-assistant</title>
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet"/>
<style>
:root{
  --bg:#fdfdf8;--surface:#f4f3ee;--border:#d4d2c9;
  --text:#4d4f46;--heading:#23251d;--accent:#F54E00;
  --green:#2e7d52;--green-s:#eaf4ee;
  --blue:#1a5fa8;--blue-s:#e8f0fb;
  --orange:#c0392b;--orange-s:#fef3f2;
  --purple:#6b3fa0;--purple-s:#f3eefb;
  --teal:#0e7490;--teal-s:#ecfeff;
  --user-bg:#23251d;--user-fg:#fdfdf8;
  --sans:'IBM Plex Sans',system-ui,sans-serif;
  --mono:'IBM Plex Mono',monospace;
}
*{box-sizing:border-box;margin:0;padding:0}
html,body{height:100%;overflow:hidden}
body{background:var(--bg);color:var(--text);font-family:var(--sans);font-size:14px;display:flex;flex-direction:column}
.hdr{display:flex;align-items:center;gap:12px;padding:12px 20px;border-bottom:1px solid var(--border);background:var(--bg);flex-shrink:0}
.hdr-icon{font-size:20px}
.hdr-title{font-size:15px;font-weight:700;color:var(--heading)}
.hdr-sub{font-size:11px;color:var(--text);opacity:.6;margin-top:1px}
#audience{margin-left:auto;background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:5px 8px;font-size:12px;font-family:var(--sans);color:var(--heading);cursor:pointer}
.badge{margin-left:10px;background:var(--surface);border:1px solid var(--border);border-radius:20px;padding:3px 11px;font-size:11px;font-weight:600;color:var(--text)}
.badge b{color:var(--accent)}
.msgs{flex:1;overflow-y:auto;padding:20px;display:flex;flex-direction:column;gap:14px}
.msg{display:flex;gap:10px;max-width:820px}
.msg.user{flex-direction:row-reverse;margin-left:auto}
.av{width:30px;height:30px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:14px;flex-shrink:0;margin-top:2px;border:1px solid var(--border);background:var(--surface)}
.msg.user .av{background:var(--user-bg);border-color:var(--user-bg);font-size:12px}
.bubble{padding:11px 15px;border-radius:12px;line-height:1.65;font-size:13.5px;max-width:740px}
.msg.user .bubble{background:var(--user-bg);color:var(--user-fg);border-radius:12px 4px 12px 12px}
.msg.bot .bubble{background:var(--surface);color:var(--heading);border:1px solid var(--border);border-radius:4px 12px 12px 12px}
.bubble p{margin-bottom:8px}
.bubble p:last-child{margin-bottom:0}
.bubble ul,.bubble ol{padding-left:18px;margin-bottom:8px}
.bubble li{margin-bottom:4px}
.bubble code{font-family:var(--mono);font-size:12px;background:rgba(0,0,0,.07);padding:1px 5px;border-radius:3px}
.fp{font-family:var(--mono);font-size:11.5px;color:var(--accent);font-weight:500}
.sec{margin:14px 0 6px;padding:6px 10px;border-radius:6px;font-size:12.5px;font-weight:700;display:flex;align-items:center;gap:6px}
.sec.create{background:var(--green-s);color:var(--green);border-left:3px solid var(--green)}
.sec.modify{background:var(--blue-s);color:var(--blue);border-left:3px solid var(--blue)}
.sec.risk{background:var(--orange-s);color:var(--orange);border-left:3px solid var(--orange)}
.sec.order{background:var(--purple-s);color:var(--purple);border-left:3px solid var(--purple)}
.sec.study{background:var(--teal-s);color:var(--teal);border-left:3px solid var(--teal)}
.sec.impact{background:var(--blue-s);color:var(--blue);border-left:3px solid var(--blue)}
.sec.change{background:var(--surface);color:var(--heading);border-left:3px solid var(--border)}
.sec.test{background:var(--green-s);color:var(--green);border-left:3px solid var(--green)}
.sec.safe{background:var(--teal-s);color:var(--teal);border-left:3px solid var(--teal)}
.sub{font-size:12px;font-weight:600;color:var(--heading);margin:8px 0 4px;padding-left:2px}
.intent-tag{display:inline-block;font-size:10px;font-weight:700;padding:2px 8px;border-radius:10px;margin-bottom:10px;letter-spacing:.04em}
.intent-tag.plan{background:#eaf4ee;color:var(--green)}
.intent-tag.impact{background:#fff0ea;color:var(--accent)}
.intent-tag.explain{background:var(--blue-s);color:var(--blue)}
.typing .bubble{padding:14px 18px}
.dots{display:flex;gap:5px;align-items:center}
.dots span{width:7px;height:7px;border-radius:50%;background:var(--text);opacity:.35;animation:bop 1.2s infinite}
.dots span:nth-child(2){animation-delay:.2s}
.dots span:nth-child(3){animation-delay:.4s}
@keyframes bop{0%,80%,100%{transform:translateY(0)}40%{transform:translateY(-6px)}}
.prog-text{font-size:11.5px;color:var(--text);opacity:.55;margin-top:8px;font-style:italic}
.sugs{padding:0 20px 10px;display:flex;gap:7px;flex-wrap:wrap;flex-shrink:0}
.sug{background:var(--surface);border:1px solid var(--border);border-radius:20px;padding:5px 12px;font-size:12px;color:var(--text);cursor:pointer;transition:border-color .15s,color .15s;white-space:nowrap}
.sug:hover{border-color:var(--accent);color:var(--accent)}
.inp-bar{padding:12px 20px;border-top:1px solid var(--border);background:var(--bg);display:flex;gap:9px;align-items:flex-end;flex-shrink:0}
textarea{flex:1;resize:none;font-family:var(--sans);font-size:14px;padding:9px 13px;border:1px solid var(--border);border-radius:10px;background:var(--surface);color:var(--heading);outline:none;line-height:1.5;min-height:42px;max-height:120px;transition:border-color .15s}
textarea:focus{border-color:var(--accent)}
textarea::placeholder{color:var(--text);opacity:.4}
#send{width:42px;height:42px;border-radius:10px;background:var(--accent);border:none;cursor:pointer;display:flex;align-items:center;justify-content:center;flex-shrink:0;transition:opacity .15s}
#send:disabled{opacity:.35;cursor:default}
#send svg{width:17px;height:17px;fill:none;stroke:#fff;stroke-width:2.2;stroke-linecap:round;stroke-linejoin:round}
</style>
</head>
<body>
<div class="hdr">
  <div class="hdr-icon">🧠</div>
  <div>
    <div class="hdr-title" id="proj-title">dev-assistant</div>
    <div class="hdr-sub">Onboarding · Implementation planning · Impact analysis · Codebase Q&A</div>
  </div>
  <select id="audience" title="Who's asking?">
    <option value="candidate">Candidate</option>
    <option value="new_hire" selected>New employee</option>
    <option value="engineer">Engineer</option>
  </select>
  <div class="badge">graphify · <b id="nc">...</b> nodes</div>
</div>
<div class="msgs" id="msgs">
  <div class="msg bot">
    <div class="av">🤖</div>
    <div class="bubble" id="welcome-bubble">
      <div class="dots"><span></span><span></span><span></span></div>
    </div>
  </div>
</div>
<div class="sugs" id="sugs"></div>
<div class="inp-bar">
  <textarea id="inp" rows="1" placeholder="Describe a new feature, a change, or ask anything…" autofocus></textarea>
  <button id="send" onclick="send()" disabled>
    <svg viewBox="0 0 24 24"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg>
  </button>
</div>
<script>
const inp=document.getElementById('inp'),msgs=document.getElementById('msgs'),btn=document.getElementById('send'),audienceSel=document.getElementById('audience');
let convoHistory=[];
fetch('/api/info').then(r=>r.json()).then(d=>{
  document.getElementById('nc').textContent=d.nodes.toLocaleString();
  document.getElementById('proj-title').textContent=d.project+' — dev-assistant';
}).catch(()=>{});
fetch('/api/getting-started').then(r=>r.json()).then(d=>{
  const wb=document.getElementById('welcome-bubble');
  wb.innerHTML=`<p>${(d.overview||'Hi! Ask me anything about this project.').replace(/</g,'&lt;')}</p>`;
  const sugs=document.getElementById('sugs');
  sugs.innerHTML='';
  (d.suggestions||[]).forEach(s=>{
    const el=document.createElement('div');el.className='sug';el.textContent=s;
    el.onclick=()=>ask(s);
    sugs.appendChild(el);
  });
}).catch(()=>{
  document.getElementById('welcome-bubble').innerHTML='<p>Hi! Ask me anything about this project — what it does, how a feature works, or what to build next.</p>';
});
inp.addEventListener('input',()=>{btn.disabled=!inp.value.trim();inp.style.height='auto';inp.style.height=Math.min(inp.scrollHeight,120)+'px';});
inp.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}});
function ask(q){inp.value=q;btn.disabled=false;send();}
function addMsg(role,html){
  const d=document.createElement('div');d.className=`msg ${role}`;
  d.innerHTML=`<div class="av">${role==='user'?'👤':'🤖'}</div><div class="bubble">${html}</div>`;
  msgs.appendChild(d);msgs.scrollTop=msgs.scrollHeight;return d;
}
const PROG={
  plan:['Searching for similar patterns...','Analysing backend structure...','Analysing frontend structure...','Generating plan...'],
  impact:['Tracing dependencies...','Mapping callers...','Assessing risk...','Writing safe steps...'],
  explain:['Querying knowledge graph...','Reading result...','Writing explanation...'],
  orient:['Reading project docs...','Building the overview...','Writing a clear answer...'],
};
let pt=null,pi=0;
function startProg(intent,el){
  const m=PROG[intent]||PROG.explain,el2=el&&el.querySelector('.prog-text');
  pi=0;if(el2)el2.textContent=m[0];
  pt=setInterval(()=>{pi=(pi+1)%m.length;if(el2)el2.textContent=m[pi];},3200);
}
function stopProg(){clearInterval(pt);}
const SEC_MAP={'Files to Create':'create','Files to Modify':'modify','Impact':'risk','Breaking Risk':'risk','Risk':'risk','Implementation Order':'order','Key Files':'study','Impact Map':'impact','What Changes':'change','Safe Implementation':'safe','Test Checklist':'test'};
function renderMd(text){
  const lines=text.split('\n');let html='',inUl=false,inOl=false;
  function closeList(){if(inUl){html+='</ul>';inUl=false;}if(inOl){html+='</ol>';inOl=false;}}
  for(let raw of lines){
    const line=raw.trim();
    if(line.startsWith('## ')){
      closeList();
      const title=line.replace(/^##\s+/,'');
      const cls=Object.entries(SEC_MAP).find(([k])=>title.includes(k))?.[1]||'change';
      html+=`<div class="sec ${cls}">${inlineRender(title)}</div>`;continue;
    }
    if(line.startsWith('### ')){closeList();html+=`<div class="sub">${inlineRender(line.replace(/^###\s+/,''))}</div>`;continue;}
    if(line.match(/^[-*]\s/)){if(!inUl){html+='<ul>';inUl=true;}if(inOl){html+='</ol>';inOl=false;}html+=`<li>${inlineRender(line.replace(/^[-*]\s+/,''))}</li>`;continue;}
    if(line.match(/^\d+\.\s/)){if(!inOl){html+='<ol>';inOl=true;}if(inUl){html+='</ul>';inUl=false;}html+=`<li>${inlineRender(line.replace(/^\d+\.\s+/,''))}</li>`;continue;}
    if(!line){closeList();continue;}
    closeList();html+=`<p>${inlineRender(line)}</p>`;
  }
  closeList();return html;
}
function inlineRender(t){
  t=t.replace(/`([^`]+)`/g,'<code>$1</code>');
  t=t.replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>');
  t=t.replace(/\*(.*?)\*/g,'<em>$1</em>');
  t=t.replace(/\b([\w\/.+-]+\.(ts|tsx|cs|py|js|html|scss|json|sh|ps1|go|java|rb))\b/g,'<span class="fp">$1</span>');
  return t;
}
function intentLabel(intent){
  const map={plan:['IMPLEMENTATION PLAN','plan'],impact:['IMPACT ANALYSIS','impact'],explain:['EXPLANATION','explain'],orient:['GETTING ORIENTED','explain']};
  const [label,cls]=map[intent]||['ANSWER','explain'];
  return `<div class="intent-tag ${cls}">${label}</div>`;
}
async function send(){
  const q=inp.value.trim();if(!q||btn.disabled)return;
  document.getElementById('sugs').style.display='none';
  inp.value='';inp.style.height='auto';btn.disabled=true;
  addMsg('user',`<p>${q.replace(/</g,'&lt;')}</p>`);
  const td=document.createElement('div');td.className='msg bot typing';
  td.innerHTML='<div class="av">🤖</div><div class="bubble"><div class="dots"><span></span><span></span><span></span></div><div class="prog-text">Analysing...</div></div>';
  msgs.appendChild(td);msgs.scrollTop=msgs.scrollHeight;
  startProg('explain',td);
  try{
    const res=await fetch('/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({
      question:q, history:convoHistory, audience:audienceSel.value
    })});
    const data=await res.json();
    stopProg();td.remove();
    if(data.error){addMsg('bot',`<p>Error: ${data.error}</p>`);}
    else{
      addMsg('bot',intentLabel(data.intent)+renderMd(data.answer));
      convoHistory.push({role:'user',content:q});
      convoHistory.push({role:'assistant',content:data.answer});
      if(convoHistory.length>12)convoHistory=convoHistory.slice(-12);
    }
  }catch(e){stopProg();td.remove();addMsg('bot','<p>Could not reach server. Is server.py running?</p>');}
}
</script>
</body>
</html>"""


# ── HTTP server ───────────────────────────────────────────────────────────────
class Handler(BaseHTTPRequestHandler):

    def do_GET(self):
        if self.path in ("/", "/chat"):
            self._send(200, "text/html; charset=utf-8", HTML.encode())
        elif self.path == "/api/info":
            payload = json.dumps({
                "nodes": graph_node_count(),
                "project": cfg.get("projectName", "Project"),
            }).encode()
            self._send(200, "application/json", payload)
        elif self.path == "/api/getting-started":
            try:
                payload = json.dumps(build_getting_started()).encode()
                self._send(200, "application/json", payload)
            except Exception as e:
                self._send(500, "application/json", json.dumps({"error": str(e)}).encode())
        else:
            self._send(404, "text/plain", b"Not found")

    def do_POST(self):
        if self.path == "/api/ask":
            try:
                length = int(self.headers.get("Content-Length", 0))
                body = json.loads(self.rfile.read(length))
                q = body.get("question", "").strip()
                history = body.get("history", [])
                audience = body.get("audience", "new_hire")
                if audience not in AUDIENCE_GUIDANCE:
                    audience = "new_hire"
                if not q:
                    self._send(400, "application/json",
                               json.dumps({"error": "No question"}).encode())
                    return
                result = handle_question(q, history=history, audience=audience)
                self._send(200, "application/json",
                           json.dumps(result).encode())
            except Exception as e:
                self._send(500, "application/json",
                           json.dumps({"error": str(e)}).encode())
        else:
            self._send(404, "text/plain", b"Not found")

    def do_OPTIONS(self):
        self.send_response(200)
        for h, v in [("Access-Control-Allow-Origin", "*"),
                     ("Access-Control-Allow-Methods", "GET, POST, OPTIONS"),
                     ("Access-Control-Allow-Headers", "Content-Type")]:
            self.send_header(h, v)
        self.end_headers()

    def _send(self, code, ctype, body):
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, fmt, *args):
        # args[0] is the request line ("GET /path HTTP/1.1") on a normal request,
        # but log_error() calls this with (code, message) instead — guard for that.
        if args and isinstance(args[0], str) and " " in args[0]:
            status = args[1] if len(args) > 1 else "-"
            path = args[0].split()[1]
        else:
            status, path = "-", (fmt % args if args else fmt)
        print(f"  [{status}] {path}")


# ── Live Sync Watcher ─────────────────────────────────────────────────────────
class LiveSyncHandler(FileSystemEventHandler if Observer else object):
    def __init__(self, root):
        self.root = root
        self.timer = None
        self.lock = threading.Lock()
        self.ignore_dirs = {".git", "node_modules", "graphify-out", ".claude", "__pycache__", ".venv", "venv"}

    def _run_graphify(self):
        try:
            subprocess.run(["graphify", ".", "--backend", "claude-cli"], cwd=self.root, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            print("  [Watcher] Graph updated automatically.")
        except Exception as e:
            print(f"  [Watcher] Failed to update graph: {e}")

    def _debounce(self):
        with self.lock:
            if self.timer:
                self.timer.cancel()
            self.timer = threading.Timer(2.0, self._run_graphify)
            self.timer.start()

    def on_any_event(self, event):
        if event.is_directory:
            return
        parts = event.src_path.split(os.sep)
        if any(ignored in parts for ignored in self.ignore_dirs):
            return
        # Debounce on actual code changes
        self._debounce()

def start_watcher(root):
    if not Observer:
        print("  [WARN] watchdog not installed. Live Sync disabled.")
        return None
    observer = Observer()
    observer.schedule(LiveSyncHandler(root), root, recursive=True)
    observer.daemon = True
    observer.start()
    return observer


# ── Entry point ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    if not os.path.exists(GRAPH):
        print(f"\n  ERROR: graph not found: {GRAPH}")
        print("  Run connect.ps1 to build the graph first.\n")
        sys.exit(1)

    n = graph_node_count()
    sep = "-" * 44
    print(f"\n  dev-assistant [{cfg.get('projectName','?')}]")
    print(f"  {sep}")
    print(f"  Graph  : {n:,} nodes")
    print(f"  Server : http://localhost:{PORT}")
    print(f"  Stop   : Ctrl+C")
    print(f"  {sep}\n")

    observer = start_watcher(ROOT)

    server = HTTPServer(("localhost", PORT), Handler)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n  Stopped.")
